apiVersion: apps/v1
kind: Deployment
metadata:
  name: <component-name>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <component-name>
  template:
    metadata:
      labels:
        app: <component-name>
    spec:
      containers:
        - name: <component-name>
          image: <image-name>:<tag>   # If you do not provide a <tag>, k8s will use `latest`
          imagePullPolicy: "Always"   # This means the container runtime will pull the image every time the pod is (re-)created. Another possible value is 'IfNotPresent'
          ports:
            - containerPort: 8000     # Exposes a port in a given container to receive traffic
          envFrom:
            - configMapRef:
                name: <component-name>-configmap
